
package com.collect.ws.autoGenerate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWebservice", targetNamespace = "http://ws.collect.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWebservice {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getValue", targetNamespace = "http://ws.collect.com/", className = "com.collect.ws.autoGenerate.GetValue")
    @ResponseWrapper(localName = "getValueResponse", targetNamespace = "http://ws.collect.com/", className = "com.collect.ws.autoGenerate.GetValueResponse")
    public String getValue(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
